// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BMO;

/************************************************************/
/**
 * 
 */
public class Adult extends Client {
	/**
	 * 
	 */
	public String occupation;
	
	/**
	 * Methods
	 */		
	public void addCheckingAccount(Checking account) {
	}
	
	public void removeCheckingAccount(Checking account) {
	}
	
	public void addInvestmentAccount(Investment account) {
	}
	
	public void removeInvestmentAccount(Investment account) {
	}
	
	public void addLoanAccount(Loan account) {
	}
	
	public void removeLoanAccount(Loan account) {
	}	
}
