// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BMO;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

/************************************************************/
/**
 * 
 */
public abstract class BankAccount {
	/**
	 * 
	 */
	public String bankAccountId;
	/**
	 * 
	 */
	public BigDecimal balance;
	/**
	 * 
	 */
	public BigDecimal totalCreditAmount;
	/**
	 * 
	 */
	public BigDecimal totalDebitAmount;
	/**
	 * 
	 */
	public Date dateOfAccountOpening;
	/**
	 * 
	 */
	public BigDecimal accountLimit;
	/**
	 * 
	 */
	public BigDecimal initialDepositAmount;
	/**
	 * 
	 */
	public String purposeOfAccount;
	
	/**
	 * Methods
	 */
	
	/**
	 * 
	 * @param amount 
	 */
	public void transferFunds(BigDecimal amount) {
	}

	/**
	 * 
	 * @param amount 
	 */
	public void receiveFunds(BigDecimal amount) {
	}

	/**
	 * 
	 * @param startDate 
	 * @param endDate 
	 */
	public void checkTransactionsHistory(Date startDate, Date endDate) {
	}

	/**
	 * 
	 * @param startDate 
	 * @param endDate 
	 */
	public void downloadStatement(Date startDate, Date endDate) {
	}

	/**
	 * 
	 */
	public void closeAccount() {
	}

	/**
	 * 
	 * @param amount 
	 */
	public void addFunds(BigDecimal amount) {
	}
	/**
	 * 
	 */
	public void addClient(Client client) {
	}
	/**
	 * 
	 */
	public void removeClient(Client client) {
	}
	/**
	 * 
	 */
	public void listClients(List<Client> clients) {
	}
	/**
	 * 
	 */
	@Override
	public String toString() {
		return "Bank Account [Account ID: " + bankAccountId + "]";
	}
}
