// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BMO;

import java.util.*;

/************************************************************/
/**
 * 
 */
public class BMO {
	/**
	 * 
	 */
	private String ceo;
	/**
	 * 
	 */
	private Set<List<String>> boardOfDirectors;
	/**
	 * 
	 */
	public BankAccount[] bankaccount;
	
	/**
	 * Getters and Setters
	 */
	public String getCeo() {
		return ceo;
	}
	public void setCeo(String ceo) {
		this.ceo = ceo;
	}
	public Set<List<String>> getBoardOfDirectors() {
		return boardOfDirectors;
	}
	public void setBoardOfDirectors(Set<List<String>> boardOfDirectors) {
		this.boardOfDirectors = boardOfDirectors;
	}
	public BankAccount[] getBankaccount() {
		return bankaccount;
	}
	public void setBankaccount(BankAccount[] bankaccount) {
		this.bankaccount = bankaccount;
	}
}
