// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BMO;

/************************************************************/
/**
 * 
 */
public class Checking extends BankAccount {
	/**
	 * 
	 */
	private String nickName;
	
	/**
	 * Getters and Setters
	 */
	public String getNickName() {
		return nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}
	
	@Override
	public String toString() {
		return "Checking Bank Account [Account ID: " + bankAccountId + "]";
	}
}
