// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BMO;

import java.util.*;

/************************************************************/
/**
 * 
 */
public class Investor extends Adult {
	/**
	 * 
	 */
	private Set<String> investmentsOfInterest;
	
	/**
	 * Getters and Setters
	 */
	public Set<String> getInvestmentsOfInterest() {
		return investmentsOfInterest;
	}

	public void setInvestmentsOfInterest(Set<String> investmentsOfInterest) {
		this.investmentsOfInterest = investmentsOfInterest;
	}
}
