// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BMO;

/************************************************************/
/**
 * 
 */
public class Loan extends BankAccount {
	/**
	 * 
	 */
	private Float interestRate;

	/**
	 * Getters and Setters
	 */
	public Float getInterestRate() {
		return interestRate;
	}

	public void setInterestRate(Float interestRate) {
		this.interestRate = interestRate;
	}
	
	@Override
	public String toString() {
		return "Loan Bank Account [Account ID: " + bankAccountId + "]";
	}
}
