// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BMO;

import java.util.List;

/************************************************************/
/**
 * 
 */
public class LoyaltyProgramActivity {
	/**
	 * 
	 */
	private String rewardActivityName;
	/**
	 * 
	 */
	private String rewardActivityCategory;
	/**
	 * 
	 */
	private String rewardActivityId;
	/**
	 * 
	 */
	private Integer pointsForParticipation;

	/**
	 * Getters and Setters
	 */
	public String getRewardActivityName() {
		return rewardActivityName;
	}
	/**
	 * 
	 */
	public void setRewardActivityName(String rewardActivityName) {
		this.rewardActivityName = rewardActivityName;
	}
	/**
	 * 
	 */
	public String getRewardActivityCategory() {
		return rewardActivityCategory;
	}
	/**
	 * 
	 */
	public void setRewardActivityCategory(String rewardActivityCategory) {
		this.rewardActivityCategory = rewardActivityCategory;
	}
	/**
	 * 
	 */
	public String getRewardActivityId() {
		return rewardActivityId;
	}
	/**
	 * 
	 */
	public void setRewardActivityId(String rewardActivityId) {
		this.rewardActivityId = rewardActivityId;
	}
	/**
	 * 
	 */
	public Integer getPointsForParticipation() {
		return pointsForParticipation;
	}
	/**
	 * 
	 */
	public void setPointsForParticipation(Integer pointsForParticipation) {
		this.pointsForParticipation = pointsForParticipation;
	}
	/**
	 * 
	 */
	public void listRewardAccounts(List<LoyaltyRewardAccount> rewardAccounts) {
	}	
	
}
