// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BMO;

/************************************************************/
/**
 * 
 */
public class Minor extends Client {
	/**
	 * 
	 */
	private String nameOfParentOrGuardian;
	/**
	 * 
	 */
	private byte[] photoOfChildRelationshipVerificationDocument;
	
	/**
	 * Getters and Setters
	 */
	public String getNameOfParentOrGuardian() {
		return nameOfParentOrGuardian;
	}

	public void setNameOfParentOrGuardian(String nameOfParentOrGuardian) {
		this.nameOfParentOrGuardian = nameOfParentOrGuardian;
	}

	public byte[] getPhotoOfChildRelationshipVerificationDocument() {
		return photoOfChildRelationshipVerificationDocument;
	}

	public void setPhotoOfChildRelationshipVerificationDocument(byte[] photoOfChildRelationshipVerificationDocument) {
		this.photoOfChildRelationshipVerificationDocument = photoOfChildRelationshipVerificationDocument;
	}
	

	/**
	 * Methods
	 */
	@Override
	public void verifyClientInfo() {
	}
}
