/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.User;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Darhlilove Botchway
 */
public class Lab3MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public Lab3MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        photoFileChooser = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        userRegistrationFormTitle = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        genderLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        ageSpinner = new javax.swing.JSpinner();
        phoneFormattedText = new javax.swing.JFormattedTextField();
        phoneLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        profilePhotoLabel = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        photoChooserButton = new javax.swing.JButton();
        submittedPhoto = new javax.swing.JLabel();
        emailLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hobbyTextArea = new javax.swing.JTextArea();
        genderComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(17, 7, 85));
        jPanel1.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N

        userRegistrationFormTitle.setFont(new java.awt.Font("Cantarell", 1, 30)); // NOI18N
        userRegistrationFormTitle.setForeground(new java.awt.Color(255, 255, 255));
        userRegistrationFormTitle.setText("User Registration Form");

        firstNameLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        firstNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        firstNameLabel.setText("First Name:");
        firstNameLabel.setToolTipText("Please enter your first name in the space provided");

        firstNameTextField.setBackground(new java.awt.Color(63, 58, 118));
        firstNameTextField.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        firstNameTextField.setForeground(new java.awt.Color(255, 255, 255));
        firstNameTextField.setToolTipText("Please enter your first name");
        firstNameTextField.setActionCommand("firstName");
        firstNameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 58, 118), 5));
        firstNameTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        firstNameTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        firstNameTextField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        firstNameTextField.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        firstNameTextField.setSelectionColor(new java.awt.Color(153, 153, 255));

        lastNameLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        lastNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        lastNameLabel.setText("Last Name:");
        lastNameLabel.setToolTipText("Please enter your last name in the space provided");

        lastNameTextField.setBackground(new java.awt.Color(63, 58, 118));
        lastNameTextField.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lastNameTextField.setForeground(new java.awt.Color(255, 255, 255));
        lastNameTextField.setToolTipText("Please enter your last name");
        lastNameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 58, 118), 5));
        lastNameTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        lastNameTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        lastNameTextField.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        lastNameTextField.setSelectionColor(new java.awt.Color(153, 153, 255));
        lastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextFieldActionPerformed(evt);
            }
        });

        genderLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        genderLabel.setForeground(new java.awt.Color(255, 255, 255));
        genderLabel.setText("Gender:");
        genderLabel.setToolTipText("Please select your gender");

        ageLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        ageLabel.setForeground(new java.awt.Color(255, 255, 255));
        ageLabel.setText("Age:");
        ageLabel.setToolTipText("Please enter your age in the space provided");

        ageSpinner.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        ageSpinner.setModel(new javax.swing.SpinnerNumberModel(Short.valueOf((short)0), Short.valueOf((short)0), Short.valueOf((short)200), Short.valueOf((short)1)));
        ageSpinner.setToolTipText("Please enter your age");
        ageSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        phoneFormattedText.setBackground(new java.awt.Color(63, 58, 118));
        phoneFormattedText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 58, 118), 5));
        phoneFormattedText.setForeground(new java.awt.Color(255, 255, 255));
        try {
            phoneFormattedText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(# # #) - # # # - # # # #")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        phoneFormattedText.setToolTipText("Please enter your phone number beginning with the area code");
        phoneFormattedText.setActionCommand("phone");
        phoneFormattedText.setCaretColor(new java.awt.Color(255, 255, 255));
        phoneFormattedText.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        phoneFormattedText.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        phoneFormattedText.setSelectionColor(new java.awt.Color(153, 153, 255));
        phoneFormattedText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneFormattedTextActionPerformed(evt);
            }
        });

        phoneLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        phoneLabel.setForeground(new java.awt.Color(255, 255, 255));
        phoneLabel.setText("Phone:");
        phoneLabel.setToolTipText("Please enter your phone number in the space provided");

        emailLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel.setText("Email:");
        emailLabel.setToolTipText("Please enter your email in the space provided");

        emailTextField.setBackground(new java.awt.Color(63, 58, 118));
        emailTextField.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        emailTextField.setForeground(new java.awt.Color(255, 255, 255));
        emailTextField.setToolTipText("Please enter your email");
        emailTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 58, 118), 5));
        emailTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        emailTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        emailTextField.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        emailTextField.setSelectionColor(new java.awt.Color(63, 58, 118));

        profilePhotoLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        profilePhotoLabel.setForeground(new java.awt.Color(255, 255, 255));
        profilePhotoLabel.setText("Profile Photo:");
        profilePhotoLabel.setToolTipText("Please select a photo for your profile using the button provided");

        submitButton.setBackground(new java.awt.Color(140, 130, 250));
        submitButton.setFont(new java.awt.Font("FreeSans", 1, 16)); // NOI18N
        submitButton.setText("Submit");
        submitButton.setToolTipText("Please click this button to submit your registration details");
        submitButton.setAlignmentX(0.5F);
        submitButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        submitButton.setBorderPainted(false);
        submitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitButton.setMultiClickThreshhold(1L);
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        photoChooserButton.setBackground(new java.awt.Color(63, 58, 118));
        photoChooserButton.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        photoChooserButton.setForeground(new java.awt.Color(255, 255, 255));
        photoChooserButton.setText("Choose File");
        photoChooserButton.setAlignmentX(0.5F);
        photoChooserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photoChooserButtonActionPerformed(evt);
            }
        });

        submittedPhoto.setFont(new java.awt.Font("sansserif", 0, 3)); // NOI18N
        submittedPhoto.setAlignmentX(0.5F);
        submittedPhoto.setIconTextGap(0);
        submittedPhoto.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                submittedPhotoComponentRemoved(evt);
            }
        });

        emailLabel1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        emailLabel1.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel1.setText("Hobbies:");
        emailLabel1.setToolTipText("Please enter your email in the space provided");

        hobbyTextArea.setBackground(new java.awt.Color(63, 58, 118));
        hobbyTextArea.setColumns(20);
        hobbyTextArea.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        hobbyTextArea.setForeground(new java.awt.Color(255, 255, 255));
        hobbyTextArea.setRows(5);
        hobbyTextArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 58, 118), 5));
        hobbyTextArea.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(hobbyTextArea);

        genderComboBox.setBackground(new java.awt.Color(63, 58, 118));
        genderComboBox.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        genderComboBox.setForeground(new java.awt.Color(255, 255, 255));
        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        genderComboBox.setSelectedIndex(-1);
        genderComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 58, 118), 5));
        genderComboBox.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(emailLabel)
                                .addComponent(ageLabel)
                                .addComponent(phoneLabel)
                                .addComponent(emailLabel1))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ageSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1)
                                .addComponent(phoneFormattedText)
                                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(profilePhotoLabel)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(photoChooserButton)
                                .addComponent(submittedPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(userRegistrationFormTitle)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(genderLabel)
                            .addComponent(lastNameLabel)
                            .addComponent(firstNameLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(firstNameTextField)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                            .addComponent(genderComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(userRegistrationFormTitle)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(genderLabel)
                    .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phoneFormattedText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(photoChooserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profilePhotoLabel))
                .addGap(18, 18, 18)
                .addComponent(submittedPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        ageSpinner.getAccessibleContext().setAccessibleName("Age");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextFieldActionPerformed

    private void phoneFormattedTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneFormattedTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneFormattedTextActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        try {
            // Initializing object of class User
            User userObject = new User();            
            
            // Initialising variables
            userObject.setFirstName(this.firstNameTextField.getText().trim().toLowerCase());
            userObject.setFirstNameProperCase();
            userObject.setLastName(this.lastNameTextField.getText().trim().toLowerCase());
            userObject.setLastNameProperCase();
            userObject.setGender(this.genderComboBox.getSelectedItem().toString());
            userObject.setEmail(this.emailTextField.getText().trim());
            userObject.setPhoneFormatted(this.phoneFormattedText.getText().replaceAll(" ", ""));
            userObject.setPhoneUnformatted();
            userObject.setAge(Integer.parseInt(this.ageSpinner.getModel().getValue().toString()));
            userObject.setHobby(this.hobbyTextArea.getText());
            
            // Check if first name is not blank or contains no text or just whitespaces OR contains other characters aside letters and "-" and "."
            if (userObject.getFirstName().isBlank() || userObject.getFirstName().toLowerCase().replaceAll("[a-z\\-.]", "").length() != 0) {
                JOptionPane.showMessageDialog(rootPane, "Please enter a valid first name.", "Input Error!", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Check if last name is not blank or contains no text or just whitespaces OR contains other characters aside letters and "-."
            if (userObject.getLastName().isBlank() || userObject.getLastName().toLowerCase().replaceAll("[a-z\\-.]", "").length() != 0) {
                JOptionPane.showMessageDialog(rootPane, "Please enter a valid last name.", "Input Error!", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Check if age is greater than 0
            if (userObject.getAge() <= 0) {
                JOptionPane.showMessageDialog(rootPane, "Please enter a valid age.", "Input Error!", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Check if phone is less than 10 digits long OR phone begins with 0
            if (userObject.getPhoneUnformatted().length() < 10 || userObject.getPhoneUnformatted().indexOf("0") == 0) {
                JOptionPane.showMessageDialog(rootPane, "Please enter a valid phone number.", "Input Error!", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Check if email is blank or contains no text or just whitespaces 
            // OR email does not contain "@" or contains more than one "@" or beigns with "@"
            // OR the text after "@" does not contain "."
            // OR there is no text before "@"
            // OR there is no text between "@" and "." 
            // OR there is no text after "."
            // OR the length of email is less than 6 characters
            if (
                userObject.getEmail().isBlank() ||                        // Email cannot be blank
                !userObject.getEmail().contains("@") ||                   // Must contain an '@'
                userObject.getEmail().indexOf("@") == 0 ||                // '@' cannot be the first character
                userObject.getEmail().lastIndexOf("@") != userObject.getEmail().indexOf("@") ||  // Multiple '@' are not allowed
                userObject.getEmail().indexOf("@") == userObject.getEmail().length() - 1 ||  // '@' cannot be the last character
                userObject.getEmail().indexOf(".", userObject.getEmail().indexOf("@")) == -1 ||  // '.' must exist after '@'
                userObject.getEmail().indexOf(".", userObject.getEmail().indexOf("@")) == userObject.getEmail().indexOf("@") + 1 ||  // '.' cannot immediately follow '@'
                userObject.getEmail().substring(userObject.getEmail().lastIndexOf(".") + 1).trim().length() < 2 ||  // Text after '.' must be at least 2 characters
                userObject.getEmail().length() < 6                        // Minimum length check
            ) {
                JOptionPane.showMessageDialog(rootPane, "Please enter a valid email.", "Input Error!", JOptionPane.ERROR_MESSAGE);
                return;
            } 
            
            // Check if hobby is not blank or contains no text or just whitespaces OR contains other characters aside letters and "-.():"
            if (userObject.getHobby().isBlank() || userObject.getHobby().toLowerCase().replaceAll("[a-z\\-.():]", "").length() != 0) {
                JOptionPane.showMessageDialog(rootPane, "Please enter a valid hobby.", "Input Error!", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Check if photo is uploaded
            if (this.submittedPhoto.getIcon() == null){
                JOptionPane.showMessageDialog(rootPane, "Please upload an image.", "Error - No image", JOptionPane.ERROR_MESSAGE);
                return;
            }

            JOptionPane.showMessageDialog(rootPane, userObject.toString(), "Account created!", HEIGHT, this.submittedPhoto.getIcon());           
        } catch (NullPointerException ne) {
            JOptionPane.showMessageDialog(rootPane, "Please select your gender", "Selection Error!", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Something went wrong!", "Ooops!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void photoChooserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photoChooserButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        
        FileNameExtensionFilter imageFilter = new FileNameExtensionFilter("Image Files (JPG, JPEG, PNG, GIF)", "jpg", "jpeg", "png", "gif");
        file.setFileFilter(imageFilter);
        
        if (file.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
            try {
                BufferedImage img = ImageIO.read(file.getSelectedFile());
                Image edited_image;
                edited_image = img.getScaledInstance(60, 80, Image.SCALE_SMOOTH);
                if (edited_image != null) {
                    this.submittedPhoto.setIcon(new ImageIcon(edited_image));
                }
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Please upload image correctly.", "Error - Incorrect image", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_photoChooserButtonActionPerformed

    private void submittedPhotoComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_submittedPhotoComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_submittedPhotoComponentRemoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab3MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab3MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab3MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab3MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab3MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageLabel;
    private javax.swing.JSpinner ageSpinner;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailLabel1;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JTextArea hobbyTextArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JFormattedTextField phoneFormattedText;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JButton photoChooserButton;
    private javax.swing.JFileChooser photoFileChooser;
    private javax.swing.JLabel profilePhotoLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel submittedPhoto;
    private javax.swing.JLabel userRegistrationFormTitle;
    // End of variables declaration//GEN-END:variables
}
