// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BMO;

import java.util.Date;
import java.util.List;
/************************************************************/
/**
 * 
 */
public abstract class Entity {
	/**
	 * 
	 */
	public String legalName;
	/**
	 * 
	 */
	public String address;
	/**
	 * 
	 */
	public String phoneNumber;
	/**
	 * 
	 */
	public String email;
	/**
	 * 
	 */
	public Date dateOfBirth;
	
	/**
	 * Methods
	 */
	public void addLoyaltyAccount(LoyaltyRewardAccount rewardAccount) {
		
	}
	/**
	 * 
	 */
	public void removeLoyaltyAccount(LoyaltyRewardAccount rewardAccount) {
		
	}
	/**
	 * 
	 */
	public void listRewardAccounts(List<LoyaltyRewardAccount> rewardAccounts) {
	}	
}
