// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BMO;

import java.util.List;

/************************************************************/
/**
 * 
 */
public class LoyaltyRewardAccount {
	/**
	 * 
	 */
	private String rewardAccountId;
	/**
	 * 
	 */
	private Integer points;

	/**
	 * Getters and Setters
	 */
	public String getRewardAccountId() {
		return rewardAccountId;
	}

	public void setRewardAccountId(String rewardAccountId) {
		this.rewardAccountId = rewardAccountId;
	}

	public Integer getPoints() {
		return points;
	}

	public void setPoints(Integer points) {
		this.points = points;
	}


	/**
	 * Methods
	 */
	
	/**
	 * 
	 * @param numberOfPoints 
	 */
	public void collectPoints(Integer numberOfPoints) {
	}

	/**
	 * 
	 * @param numberOfPoints 
	 */
	public void usePoints(Integer numberOfPoints) {
	}

	/**
	 * 
	 * @param activityId 
	 */
	public void participateInActivity(String activityId) {
	}

	/**
	 * 
	 */
	public void viewRewardActivities() {
	}
	
	/**
	 * 
	 */
	public void listRewardActivities(List<LoyaltyProgramActivity> activities) {
	}
	/**
	 * 
	 */
	public void addClient(Client client) {
	}
	/**
	 * 
	 */
	public void removeClient(Client client) {
	}
	/**
	 * 
	 */
	public void listClients(List<Client> clients) {
	}
	/**
	 * 
	 */
	public void addNonClient(NonClient nonClient) {
	}
	/**
	 * 
	 */
	public void removeNonClient(NonClient nonClient) {
	}
	/**
	 * 
	 */
	public void listNonClients(List<NonClient> nonClients) {
	}
}
