// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BMO;

import java.util.Set;

/************************************************************/
/**
 * 
 */
public class NonClient extends Entity {
	/**
	 * 
	 */
	private Set<String> banksPatronised;

	/**
	 * Getters and Setters
	 */
	public Set<String> getBanksPatronised() {
		return banksPatronised;
	}

	public void setBanksPatronised(Set<String> banksPatronised) {
		this.banksPatronised = banksPatronised;
	}
	
	
}
