// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BMO;

import java.util.List;
import java.util.Set;

/************************************************************/
/**
 * 
 */
public class SmallBusiness extends Adult {
	/**
	 * 
	 */
	private String ceo;
	/**
	 * 
	 */
	private Set<List<String>> nameAndDesignationOfSignatories;
	/**
	 * 
	 */
	private String taxIdentificationNumber;
	/**
	 * 
	 */
	private byte[] identityVerificationDocumentsOfSignatories;
	/**
	 * 
	 */
	private String sectorOfBusiness;
	/**
	 * 
	 */
	private byte[] photoSampleOfSignatures;

	/**
	 * Methods
	 */
	public void verifyClientInfo() {
	}

	/**
	 * Getters and Setters
	 */
	public String getCeo() {
		return ceo;
	}

	public void setCeo(String ceo) {
		this.ceo = ceo;
	}

	public Set<List<String>> getNameAndDesignationOfSignatories() {
		return nameAndDesignationOfSignatories;
	}

	public void setNameAndDesignationOfSignatories(Set<List<String>> nameAndDesignationOfSignatories) {
		this.nameAndDesignationOfSignatories = nameAndDesignationOfSignatories;
	}

	public String getTaxIdentificationNumber() {
		return taxIdentificationNumber;
	}

	public void setTaxIdentificationNumber(String taxIdentificationNumber) {
		this.taxIdentificationNumber = taxIdentificationNumber;
	}

	public byte[] getIdentityVerificationDocumentsOfSignatories() {
		return identityVerificationDocumentsOfSignatories;
	}

	public void setIdentityVerificationDocumentsOfSignatories(byte[] identityVerificationDocumentsOfSignatories) {
		this.identityVerificationDocumentsOfSignatories = identityVerificationDocumentsOfSignatories;
	}

	public String getSectorOfBusiness() {
		return sectorOfBusiness;
	}

	public void setSectorOfBusiness(String sectorOfBusiness) {
		this.sectorOfBusiness = sectorOfBusiness;
	}

	public byte[] getPhotoSampleOfSignatures() {
		return photoSampleOfSignatures;
	}

	public void setPhotoSampleOfSignatures(byte[] photoSampleOfSignatures) {
		this.photoSampleOfSignatures = photoSampleOfSignatures;
	}	
}
