/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.CardLayout;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.User;
import utility.DatabaseConnector;

/**
 *
 * @author nana
 */
public class FormJPanel extends javax.swing.JPanel {

    JPanel bottomPanel;
    
    /**
     * Creates new form FormJPanel
     */
    public FormJPanel() {
        initComponents();
    }
    
    public FormJPanel(JPanel bottomPanel) {
        initComponents();
        this.bottomPanel = bottomPanel;
    }

    public static int calculateAge(Date date) {
            LocalDate birthDay;
            LocalDate today;
            int age;
            int monthDifference;

            birthDay = date.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
            today = LocalDate.now();
            age = today.getYear() - birthDay.getYear();
            monthDifference = today.getMonthValue() - birthDay.getMonthValue();

            if(monthDifference < 0 || (monthDifference == 0 && today.getDayOfMonth() < birthDay.getDayOfMonth())){
                age--;
            }
            return age;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emailLabel = new javax.swing.JLabel();
        userRegistrationFormTitle = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        dateOfBirthLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        lastNameLabel = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        submittedPhoto = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        emailLabel1 = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hobbyTextArea = new javax.swing.JTextArea();
        ageSpinner = new javax.swing.JSpinner();
        phoneFormattedText = new javax.swing.JFormattedTextField();
        genderComboBox = new javax.swing.JComboBox<>();
        phoneLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        dateOfBirthDateChooser = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(17, 7, 85));
        setPreferredSize(new java.awt.Dimension(1000, 620));

        emailLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel.setText("Email:");
        emailLabel.setToolTipText("Please enter your email in the space provided");

        userRegistrationFormTitle.setFont(new java.awt.Font("Cantarell", 1, 30)); // NOI18N
        userRegistrationFormTitle.setForeground(new java.awt.Color(255, 255, 255));
        userRegistrationFormTitle.setText("User Registration Form");

        firstNameLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        firstNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        firstNameLabel.setText("First Name:");
        firstNameLabel.setToolTipText("Please enter your first name in the space provided");

        dateOfBirthLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        dateOfBirthLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateOfBirthLabel.setText("Date of Birth:");
        dateOfBirthLabel.setToolTipText("Please select a photo for your profile using the button provided");

        firstNameTextField.setBackground(new java.awt.Color(63, 58, 118));
        firstNameTextField.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        firstNameTextField.setForeground(new java.awt.Color(255, 255, 255));
        firstNameTextField.setToolTipText("Please enter your first name");
        firstNameTextField.setActionCommand("firstName");
        firstNameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 58, 118), 5));
        firstNameTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        firstNameTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        firstNameTextField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        firstNameTextField.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        firstNameTextField.setSelectionColor(new java.awt.Color(153, 153, 255));

        submitButton.setBackground(new java.awt.Color(140, 130, 250));
        submitButton.setFont(new java.awt.Font("FreeSans", 1, 16)); // NOI18N
        submitButton.setText("Submit");
        submitButton.setToolTipText("Please click this button to submit your registration details");
        submitButton.setAlignmentX(0.5F);
        submitButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        submitButton.setBorderPainted(false);
        submitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitButton.setMultiClickThreshhold(1L);
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        lastNameLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        lastNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        lastNameLabel.setText("Last Name:");
        lastNameLabel.setToolTipText("Please enter your last name in the space provided");

        lastNameTextField.setBackground(new java.awt.Color(63, 58, 118));
        lastNameTextField.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lastNameTextField.setForeground(new java.awt.Color(255, 255, 255));
        lastNameTextField.setToolTipText("Please enter your last name");
        lastNameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 58, 118), 5));
        lastNameTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        lastNameTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        lastNameTextField.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        lastNameTextField.setSelectionColor(new java.awt.Color(153, 153, 255));
        lastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextFieldActionPerformed(evt);
            }
        });

        submittedPhoto.setFont(new java.awt.Font("sansserif", 0, 3)); // NOI18N
        submittedPhoto.setAlignmentX(0.5F);
        submittedPhoto.setIconTextGap(0);
        submittedPhoto.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                submittedPhotoComponentRemoved(evt);
            }
        });

        genderLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        genderLabel.setForeground(new java.awt.Color(255, 255, 255));
        genderLabel.setText("Gender:");
        genderLabel.setToolTipText("Please select your gender");

        emailLabel1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        emailLabel1.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel1.setText("Hobbies:");
        emailLabel1.setToolTipText("Please enter your email in the space provided");

        ageLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        ageLabel.setForeground(new java.awt.Color(255, 255, 255));
        ageLabel.setText("Age:");
        ageLabel.setToolTipText("Please enter your age in the space provided");

        hobbyTextArea.setBackground(new java.awt.Color(63, 58, 118));
        hobbyTextArea.setColumns(20);
        hobbyTextArea.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        hobbyTextArea.setForeground(new java.awt.Color(255, 255, 255));
        hobbyTextArea.setLineWrap(true);
        hobbyTextArea.setRows(5);
        hobbyTextArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 58, 118), 5));
        hobbyTextArea.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(hobbyTextArea);

        ageSpinner.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        ageSpinner.setModel(new javax.swing.SpinnerNumberModel(Short.valueOf((short)0), Short.valueOf((short)0), Short.valueOf((short)200), Short.valueOf((short)1)));
        ageSpinner.setToolTipText("Please enter your age");
        ageSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        phoneFormattedText.setBackground(new java.awt.Color(63, 58, 118));
        phoneFormattedText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 58, 118), 5));
        phoneFormattedText.setForeground(new java.awt.Color(255, 255, 255));
        try {
            phoneFormattedText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(# # #) - # # # - # # # #")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        phoneFormattedText.setToolTipText("Please enter your phone number beginning with the area code");
        phoneFormattedText.setActionCommand("phone");
        phoneFormattedText.setCaretColor(new java.awt.Color(255, 255, 255));
        phoneFormattedText.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        phoneFormattedText.setPreferredSize(new java.awt.Dimension(64, 32));
        phoneFormattedText.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        phoneFormattedText.setSelectionColor(new java.awt.Color(153, 153, 255));
        phoneFormattedText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneFormattedTextActionPerformed(evt);
            }
        });

        genderComboBox.setBackground(new java.awt.Color(63, 58, 118));
        genderComboBox.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        genderComboBox.setForeground(new java.awt.Color(255, 255, 255));
        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        genderComboBox.setSelectedIndex(-1);
        genderComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 58, 118), 5));
        genderComboBox.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        genderComboBox.setPreferredSize(new java.awt.Dimension(64, 36));

        phoneLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        phoneLabel.setForeground(new java.awt.Color(255, 255, 255));
        phoneLabel.setText("Phone:");
        phoneLabel.setToolTipText("Please enter your phone number in the space provided");

        emailTextField.setBackground(new java.awt.Color(63, 58, 118));
        emailTextField.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        emailTextField.setForeground(new java.awt.Color(255, 255, 255));
        emailTextField.setToolTipText("Please enter your email");
        emailTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 58, 118), 5));
        emailTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        emailTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        emailTextField.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        emailTextField.setSelectionColor(new java.awt.Color(63, 58, 118));

        dateOfBirthDateChooser.setBackground(new java.awt.Color(63, 58, 118));
        dateOfBirthDateChooser.setForeground(new java.awt.Color(255, 255, 255));
        dateOfBirthDateChooser.setToolTipText("Please select your date of birth");
        dateOfBirthDateChooser.setDateFormatString("MMMM dd, yyyy");
        dateOfBirthDateChooser.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        dateOfBirthDateChooser.setMaxSelectableDate(new java.util.Date(1740808867000L));
        dateOfBirthDateChooser.setMinSelectableDate(new java.util.Date(-2208967133000L));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(userRegistrationFormTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(emailLabel)
                                    .addComponent(ageLabel)
                                    .addComponent(phoneLabel)
                                    .addComponent(emailLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ageSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1)
                                    .addComponent(emailTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                                    .addComponent(phoneFormattedText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(firstNameLabel)
                                    .addComponent(lastNameLabel)
                                    .addComponent(genderLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(firstNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                                    .addComponent(lastNameTextField)
                                    .addComponent(genderComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dateOfBirthLabel)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(submittedPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateOfBirthDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(373, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(userRegistrationFormTitle)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phoneFormattedText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateOfBirthDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateOfBirthLabel))
                .addGap(28, 28, 28)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(submittedPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        
        try {
            // Initializing object of class User
            User userObject = new User();

            // Initialising userObject variables
            userObject.setFirstName(this.firstNameTextField.getText().trim().toLowerCase());
            userObject.setLastName(this.lastNameTextField.getText().trim().toLowerCase());
            userObject.setFirstNameProperCase();
            userObject.setLastNameProperCase();
            userObject.setGender(this.genderComboBox.getSelectedItem().toString());
            userObject.setEmail(this.emailTextField.getText().trim());
            userObject.setPhoneFormatted(this.phoneFormattedText.getText());
            userObject.setPhoneUnformatted();
            userObject.setAge(Integer.parseInt(this.ageSpinner.getModel().getValue().toString()));
            userObject.setHobby(this.hobbyTextArea.getText().trim().replaceAll("\\s+|\n", " "));
            userObject.setDateOfBirth(this.dateOfBirthDateChooser.getDate());
            
            // Parsing and initialising string date of birth
            Date selectedDate = this.dateOfBirthDateChooser.getDate();
            LocalDate localDate = selectedDate.toInstant()
                                           .atZone(java.time.ZoneId.systemDefault())
                                           .toLocalDate();
            String parsedDate = localDate.getMonth().name().substring(0,1) + localDate.getMonth().name().substring(1).toLowerCase() 
                                        + " " + localDate.getDayOfMonth() + ", "+ localDate.getYear();
            userObject.setDateOfBirthString(parsedDate);
            

            // Check if first name is not blank or contains no text or just whitespaces OR contains other characters aside letters and "-" and "."
            if (userObject.getFirstName().isBlank() || userObject.getFirstName().replaceAll("[a-z\\-. ]", "").length() != 0) {
                JOptionPane.showMessageDialog(this, "Please enter a valid first name.", "Input Error!", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Check if last name is not blank or contains no text or just whitespaces OR contains other characters aside letters and "-."
            if (userObject.getLastName().isBlank() || userObject.getLastName().replaceAll("[a-z\\-. ]", "").length() != 0) {
                JOptionPane.showMessageDialog(this, "Please enter a valid last name.", "Input Error!", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Initialise Proper case for first and last name after verifying input 
             userObject.setFirstNameProperCase();
             userObject.setLastNameProperCase();

            // Check if age is greater than 0
            if (userObject.getAge() <= 0) {
                JOptionPane.showMessageDialog(this, "Please enter a valid age.", "Input Error!", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Check if phone is less than 10 digits long OR phone begins with 0
            if (userObject.getPhoneUnformatted().length() < 10 || userObject.getPhoneUnformatted().indexOf("0") == 0) {
                JOptionPane.showMessageDialog(this, "Please enter a valid phone number.", "Input Error!", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Check if email is blank or contains no text or just whitespaces
            // OR email does not contain "@" or contains more than one "@" or beigns with "@"
            // OR the text after "@" does not contain "."
            // OR there is no text before "@"
            // OR there is no text between "@" and "."
            // OR there is no text after "."
            // OR the length of email is less than 6 characters
            if (
                userObject.getEmail().isBlank() ||                        // Email cannot be blank
                !userObject.getEmail().contains("@") ||                   // Must contain an '@'
                userObject.getEmail().indexOf("@") == 0 ||                // '@' cannot be the first character
                userObject.getEmail().lastIndexOf("@") != userObject.getEmail().indexOf("@") ||  // Multiple '@' are not allowed
                userObject.getEmail().indexOf("@") == userObject.getEmail().length() - 1 ||  // '@' cannot be the last character
                userObject.getEmail().indexOf(".", userObject.getEmail().indexOf("@")) == -1 ||  // '.' must exist after '@'
                userObject.getEmail().indexOf(".", userObject.getEmail().indexOf("@")) == userObject.getEmail().indexOf("@") + 1 ||  // '.' cannot immediately follow '@'
                userObject.getEmail().substring(userObject.getEmail().lastIndexOf(".") + 1).trim().length() < 2 ||  // Text after '.' must be at least 2 characters
                userObject.getEmail().length() < 6                        // Minimum length check
            ) {
                JOptionPane.showMessageDialog(this, "Please enter a valid email.", "Input Error!", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Check if hobby is not blank or contains no text or just whitespaces OR contains other characters aside letters and "-.():\n"
            if (userObject.getHobby().isBlank() || userObject.getHobby().toLowerCase().replaceAll("[a-z\\-.,():\n ]", "").length() != 0) {
                JOptionPane.showMessageDialog(this, "Please enter a valid hobby.", "Input Error!", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Check if date is selected OR date selected matches age
            if (userObject.getDateOfBirth() == null){
                JOptionPane.showMessageDialog(this, "Please select your date of birth", "Input Error!", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Check if date selected matches age
            if (calculateAge(userObject.getDateOfBirth()) != userObject.getAge()){
                JOptionPane.showMessageDialog(this, "Your age does not match your date of birth", "Input Error!", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Adding student to schooldb
            DatabaseConnector.addUser(userObject);
            System.out.println("Student add to database!");
            
            JOptionPane.showMessageDialog(this, userObject.toString(), "Student data saved successfully!", HEIGHT);
            ViewJPanel viewJPanelObject = new ViewJPanel();
            this.bottomPanel.add(viewJPanelObject);
            CardLayout layout = (CardLayout) this.bottomPanel.getLayout();
            layout.next(bottomPanel);

        } catch (NullPointerException ne) {
            JOptionPane.showMessageDialog(this, "Please provide valid responses for all the fields", "Input Error!", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Something went wrong!", "Ooops!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void lastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextFieldActionPerformed

    private void submittedPhotoComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_submittedPhotoComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_submittedPhotoComponentRemoved

    private void phoneFormattedTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneFormattedTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneFormattedTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageLabel;
    private javax.swing.JSpinner ageSpinner;
    private com.toedter.calendar.JDateChooser dateOfBirthDateChooser;
    private javax.swing.JLabel dateOfBirthLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailLabel1;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JTextArea hobbyTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JFormattedTextField phoneFormattedText;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel submittedPhoto;
    private javax.swing.JLabel userRegistrationFormTitle;
    // End of variables declaration//GEN-END:variables
}
