/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.User;
import utility.DatabaseConnector;

/**
 *
 * @author nana
 */
public class ViewJPanel extends javax.swing.JPanel {

    User userObject;
    ArrayList <User> users;
    
    /**
     * Creates new form FormJPanel
     */
    public ViewJPanel() {
        initComponents();
        populateTable();
        
    }
    
    public final void setAllFields(){
        this.firstNameTextField.setText(userObject.getFirstName());
        this.lastNameTextField.setText(userObject.getLastName());
        this.genderComboBox.setSelectedItem(userObject.getGender());
        this.ageSpinner.setValue(userObject.getAge());
        this.phoneFormattedText.setText(userObject.getPhoneFormatted());
        this.emailTextField.setText(userObject.getEmail());
        this.hobbyTextArea.setText(userObject.getHobby());
        this.dateOfBirthTextField.setText(userObject.getDateOfBirthString());
    }
    
    public final void clearAllFields(){
        this.firstNameTextField.setText(null);
        this.lastNameTextField.setText(null);
        this.genderComboBox.setSelectedItem(null);
        this.ageSpinner.setValue(0);
        this.phoneFormattedText.setText(null);
        this.emailTextField.setText(null);
        this.hobbyTextArea.setText(null);
        this.dateOfBirthTextField.setText(null);
    }
    
    public void toggleFormEnableProperty(Boolean b) {
        this.firstNameTextField.setEnabled(b);
        this.lastNameTextField.setEnabled(b);
        this.genderComboBox.setEnabled(b);
        this.emailTextField.setEnabled(b);
        this.phoneFormattedText.setEnabled(b);
        this.ageSpinner.setEnabled(b);
        this.dateOfBirthTextField.setEnabled(b);
        this.hobbyTextArea.setEnabled(b);
    };

    public final void populateTable(){
        this.users = DatabaseConnector.getUsers();
        
        DefaultTableModel model = (DefaultTableModel) this.studentsJTable.getModel();
        model.setRowCount(0);
        
        for (User u: users) {
            Object [] row = new Object[9];
            row[0] = u.getUserId();
            row[1] = u.getFirstName();
            row[2] = u.getLastName();
            row[3] = u.getGender();
            row[4] = u.getEmail();
            row[5] = u.getPhoneFormatted();
            row[6] = u.getAge();
            row[7] = u.getDateOfBirthString();
            row[8] = u.getHobby();
            model.addRow(row);
        }
        
    };
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emailLabel = new javax.swing.JLabel();
        userRegistrationFormTitle = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        genderLabel = new javax.swing.JLabel();
        hobbiesLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hobbyTextArea = new javax.swing.JTextArea();
        ageSpinner = new javax.swing.JSpinner();
        phoneFormattedText = new javax.swing.JFormattedTextField();
        genderComboBox = new javax.swing.JComboBox<>();
        phoneLabel = new javax.swing.JLabel();
        DateOfBirthLabel = new javax.swing.JLabel();
        dateOfBirthTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        studentsJTable = new javax.swing.JTable();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(17, 7, 85));
        setPreferredSize(new java.awt.Dimension(1000, 620));

        emailLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel.setText("Email:");
        emailLabel.setToolTipText("Please enter your email in the space provided");

        userRegistrationFormTitle.setFont(new java.awt.Font("Cantarell", 1, 30)); // NOI18N
        userRegistrationFormTitle.setForeground(new java.awt.Color(255, 255, 255));
        userRegistrationFormTitle.setText("User Details Submitted");

        emailTextField.setBackground(new java.awt.Color(63, 58, 118));
        emailTextField.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        emailTextField.setForeground(new java.awt.Color(255, 255, 255));
        emailTextField.setToolTipText("Please enter your email");
        emailTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 58, 118), 5));
        emailTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        emailTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        emailTextField.setEnabled(false);
        emailTextField.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        emailTextField.setSelectionColor(new java.awt.Color(63, 58, 118));

        firstNameLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        firstNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        firstNameLabel.setText("First Name:");
        firstNameLabel.setToolTipText("Please enter your first name in the space provided");

        firstNameTextField.setBackground(new java.awt.Color(63, 58, 118));
        firstNameTextField.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        firstNameTextField.setForeground(new java.awt.Color(255, 255, 255));
        firstNameTextField.setToolTipText("Please enter your first name");
        firstNameTextField.setActionCommand("firstName");
        firstNameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 58, 118), 5));
        firstNameTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        firstNameTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        firstNameTextField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        firstNameTextField.setEnabled(false);
        firstNameTextField.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        firstNameTextField.setSelectionColor(new java.awt.Color(153, 153, 255));

        lastNameLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        lastNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        lastNameLabel.setText("Last Name:");
        lastNameLabel.setToolTipText("Please enter your last name in the space provided");

        lastNameTextField.setBackground(new java.awt.Color(63, 58, 118));
        lastNameTextField.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lastNameTextField.setForeground(new java.awt.Color(255, 255, 255));
        lastNameTextField.setToolTipText("Please enter your last name");
        lastNameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 58, 118), 5));
        lastNameTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        lastNameTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        lastNameTextField.setEnabled(false);
        lastNameTextField.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        lastNameTextField.setSelectionColor(new java.awt.Color(153, 153, 255));
        lastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextFieldActionPerformed(evt);
            }
        });

        genderLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        genderLabel.setForeground(new java.awt.Color(255, 255, 255));
        genderLabel.setText("Gender:");
        genderLabel.setToolTipText("Please select your gender");

        hobbiesLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        hobbiesLabel.setForeground(new java.awt.Color(255, 255, 255));
        hobbiesLabel.setText("Hobbies:");
        hobbiesLabel.setToolTipText("Please enter your email in the space provided");

        ageLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        ageLabel.setForeground(new java.awt.Color(255, 255, 255));
        ageLabel.setText("Age:");
        ageLabel.setToolTipText("Please enter your age in the space provided");

        hobbyTextArea.setBackground(new java.awt.Color(63, 58, 118));
        hobbyTextArea.setColumns(20);
        hobbyTextArea.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        hobbyTextArea.setForeground(new java.awt.Color(255, 255, 255));
        hobbyTextArea.setLineWrap(true);
        hobbyTextArea.setRows(5);
        hobbyTextArea.setToolTipText("Please enter your hobbies");
        hobbyTextArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 58, 118), 5));
        hobbyTextArea.setCaretColor(new java.awt.Color(255, 255, 255));
        hobbyTextArea.setEnabled(false);
        jScrollPane1.setViewportView(hobbyTextArea);

        ageSpinner.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        ageSpinner.setModel(new javax.swing.SpinnerNumberModel(Short.valueOf((short)0), Short.valueOf((short)0), Short.valueOf((short)200), Short.valueOf((short)1)));
        ageSpinner.setToolTipText("Please enter your age");
        ageSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ageSpinner.setEnabled(false);

        phoneFormattedText.setBackground(new java.awt.Color(63, 58, 118));
        phoneFormattedText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 58, 118), 5));
        phoneFormattedText.setForeground(new java.awt.Color(255, 255, 255));
        try {
            phoneFormattedText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(# # #) - # # # - # # # #")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        phoneFormattedText.setToolTipText("Please enter your phone number beginning with the area code");
        phoneFormattedText.setActionCommand("phone");
        phoneFormattedText.setCaretColor(new java.awt.Color(255, 255, 255));
        phoneFormattedText.setEnabled(false);
        phoneFormattedText.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        phoneFormattedText.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        phoneFormattedText.setSelectionColor(new java.awt.Color(153, 153, 255));
        phoneFormattedText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneFormattedTextActionPerformed(evt);
            }
        });

        genderComboBox.setBackground(new java.awt.Color(63, 58, 118));
        genderComboBox.setEditable(true);
        genderComboBox.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        genderComboBox.setForeground(new java.awt.Color(255, 255, 255));
        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        genderComboBox.setSelectedIndex(-1);
        genderComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 58, 118), 5));
        genderComboBox.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        genderComboBox.setEnabled(false);

        phoneLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        phoneLabel.setForeground(new java.awt.Color(255, 255, 255));
        phoneLabel.setText("Phone:");
        phoneLabel.setToolTipText("Please enter your phone number in the space provided");

        DateOfBirthLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        DateOfBirthLabel.setForeground(new java.awt.Color(255, 255, 255));
        DateOfBirthLabel.setText("Date of Birth:");
        DateOfBirthLabel.setToolTipText("Please select a photo for your profile using the button provided");

        dateOfBirthTextField.setBackground(new java.awt.Color(63, 58, 118));
        dateOfBirthTextField.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        dateOfBirthTextField.setForeground(new java.awt.Color(255, 255, 255));
        dateOfBirthTextField.setToolTipText("Please enter your email");
        dateOfBirthTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 58, 118), 5));
        dateOfBirthTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        dateOfBirthTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        dateOfBirthTextField.setEnabled(false);
        dateOfBirthTextField.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        dateOfBirthTextField.setSelectionColor(new java.awt.Color(63, 58, 118));

        studentsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Student ID", "First Name", "Last Name", "Gender", "Email", "Phone Number", "Age", "Date of Birth", "Hobbies"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(studentsJTable);

        editButton.setBackground(new java.awt.Color(140, 130, 250));
        editButton.setFont(new java.awt.Font("FreeSans", 1, 16)); // NOI18N
        editButton.setText("Edit");
        editButton.setToolTipText("Please click this button to submit your registration details");
        editButton.setAlignmentX(0.5F);
        editButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        editButton.setBorderPainted(false);
        editButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editButton.setMultiClickThreshhold(1L);
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(140, 130, 250));
        deleteButton.setFont(new java.awt.Font("FreeSans", 1, 16)); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.setToolTipText("Please click this button to submit your registration details");
        deleteButton.setAlignmentX(0.5F);
        deleteButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        deleteButton.setBorderPainted(false);
        deleteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteButton.setMultiClickThreshhold(1L);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        updateButton.setBackground(new java.awt.Color(140, 130, 250));
        updateButton.setFont(new java.awt.Font("FreeSans", 1, 16)); // NOI18N
        updateButton.setText("Update");
        updateButton.setToolTipText("Please click this button to submit your registration details");
        updateButton.setAlignmentX(0.5F);
        updateButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        updateButton.setBorderPainted(false);
        updateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateButton.setMultiClickThreshhold(1L);
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(genderLabel)
                    .addComponent(lastNameLabel)
                    .addComponent(firstNameLabel)
                    .addComponent(ageLabel)
                    .addComponent(phoneLabel)
                    .addComponent(emailLabel)
                    .addComponent(hobbiesLabel)
                    .addComponent(DateOfBirthLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(userRegistrationFormTitle)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(genderComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ageSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1)
                                .addComponent(phoneFormattedText)
                                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dateOfBirthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(208, 208, 208))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(userRegistrationFormTitle)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameLabel)
                            .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameLabel)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genderLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ageSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ageLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneFormattedText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hobbiesLabel)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateOfBirthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DateOfBirthLabel))))
                .addGap(18, 18, 18)
                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(235, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextFieldActionPerformed

    private void phoneFormattedTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneFormattedTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneFormattedTextActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        
        int selectedStudentIndex = this.studentsJTable.getSelectedRow();
        
        try {
            this.userObject = this.users.get(selectedStudentIndex);
            setAllFields();
            toggleFormEnableProperty(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Something went wrong!", "Ooops!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        int selectedStudentIndex = this.studentsJTable.getSelectedRow();
        
        try {
            this.userObject = this.users.get(selectedStudentIndex);
            String studentFirstName = userObject.getFirstName();
            
            DatabaseConnector.deleteUser(userObject);
            JOptionPane.showMessageDialog(this, studentFirstName + " has deleted from the database successfully", "Success!", JOptionPane.INFORMATION_MESSAGE);
            populateTable();
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Something went wrong!", "Ooops!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        User updatedUser = new User();
        updatedUser.setFirstName(this.firstNameTextField.getText());
        updatedUser.setFirstNameProperCase();
        updatedUser.setLastName(this.lastNameTextField.getText());
        updatedUser.setLastNameProperCase();
        updatedUser.setGender(this.genderComboBox.getSelectedItem().toString());
        updatedUser.setEmail(this.emailTextField.getText().trim());
        updatedUser.setPhoneFormatted(this.phoneFormattedText.getText());
        updatedUser.setPhoneUnformatted();
        updatedUser.setAge(Integer.parseInt(this.ageSpinner.getModel().getValue().toString()));
        updatedUser.setHobby(this.hobbyTextArea.getText().trim().replaceAll("\\s+|\n", " "));
        updatedUser.setDateOfBirthString(this.dateOfBirthTextField.getText());
        
        try {
            String studentFirstName = userObject.getFirstName();
            DatabaseConnector.updateUser(userObject, updatedUser);
            
            JOptionPane.showMessageDialog(this, studentFirstName + "'s information has been updated successfully", "Success!", JOptionPane.INFORMATION_MESSAGE);
            populateTable();
            clearAllFields();
            toggleFormEnableProperty(false);
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Something went wrong!", "Ooops!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_updateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DateOfBirthLabel;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JSpinner ageSpinner;
    private javax.swing.JTextField dateOfBirthTextField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel hobbiesLabel;
    private javax.swing.JTextArea hobbyTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JFormattedTextField phoneFormattedText;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTable studentsJTable;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel userRegistrationFormTitle;
    // End of variables declaration//GEN-END:variables
}
