/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.Icon;
import model.User;

/**
 *
 * @author nana
 */
public class ViewJPanel extends javax.swing.JPanel {

    User userObject;
    
    /**
     * Creates new form FormJPanel
     */
    public ViewJPanel() {
        initComponents();
    }
    
    public ViewJPanel(User userObject) {
        initComponents();
        this.userObject = userObject;
        setAllFields();
    }

    public final void setAllFields(){
        this.firstNameTextField.setText(userObject.getFirstNameProperCase());
        this.lastNameTextField.setText(userObject.getLastNameProperCase());
        this.genderComboBox.setSelectedItem(userObject.getGender());
        this.ageSpinner.setValue(userObject.getAge());
        this.phoneFormattedText.setText(userObject.getPhoneFormatted());
        this.emailTextField.setText(userObject.getEmail());
        this.hobbyTextArea.setText(userObject.getHobby());
        this.photoSubmitted.setIcon((Icon) userObject.getProfilePhoto());
        this.dateOfBirthTextField.setText(userObject.getDateOfBirthString());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emailLabel = new javax.swing.JLabel();
        userRegistrationFormTitle = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        profilePhotoLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        photoSubmitted = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        hobbiesLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hobbyTextArea = new javax.swing.JTextArea();
        ageSpinner = new javax.swing.JSpinner();
        phoneFormattedText = new javax.swing.JFormattedTextField();
        genderComboBox = new javax.swing.JComboBox<>();
        phoneLabel = new javax.swing.JLabel();
        DateOfBirthLabel = new javax.swing.JLabel();
        dateOfBirthTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(17, 7, 85));
        setPreferredSize(new java.awt.Dimension(1000, 620));

        emailLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel.setText("Email:");
        emailLabel.setToolTipText("Please enter your email in the space provided");

        userRegistrationFormTitle.setFont(new java.awt.Font("Cantarell", 1, 30)); // NOI18N
        userRegistrationFormTitle.setForeground(new java.awt.Color(255, 255, 255));
        userRegistrationFormTitle.setText("User Details Submitted");

        emailTextField.setEditable(false);
        emailTextField.setBackground(new java.awt.Color(63, 58, 118));
        emailTextField.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        emailTextField.setForeground(new java.awt.Color(255, 255, 255));
        emailTextField.setToolTipText("Please enter your email");
        emailTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 58, 118), 5));
        emailTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        emailTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        emailTextField.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        emailTextField.setSelectionColor(new java.awt.Color(63, 58, 118));

        firstNameLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        firstNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        firstNameLabel.setText("First Name:");
        firstNameLabel.setToolTipText("Please enter your first name in the space provided");

        profilePhotoLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        profilePhotoLabel.setForeground(new java.awt.Color(255, 255, 255));
        profilePhotoLabel.setText("Profile Photo:");
        profilePhotoLabel.setToolTipText("Please select a photo for your profile using the button provided");

        firstNameTextField.setEditable(false);
        firstNameTextField.setBackground(new java.awt.Color(63, 58, 118));
        firstNameTextField.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        firstNameTextField.setForeground(new java.awt.Color(255, 255, 255));
        firstNameTextField.setToolTipText("Please enter your first name");
        firstNameTextField.setActionCommand("firstName");
        firstNameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 58, 118), 5));
        firstNameTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        firstNameTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        firstNameTextField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        firstNameTextField.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        firstNameTextField.setSelectionColor(new java.awt.Color(153, 153, 255));

        lastNameLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        lastNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        lastNameLabel.setText("Last Name:");
        lastNameLabel.setToolTipText("Please enter your last name in the space provided");

        lastNameTextField.setEditable(false);
        lastNameTextField.setBackground(new java.awt.Color(63, 58, 118));
        lastNameTextField.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lastNameTextField.setForeground(new java.awt.Color(255, 255, 255));
        lastNameTextField.setToolTipText("Please enter your last name");
        lastNameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 58, 118), 5));
        lastNameTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        lastNameTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        lastNameTextField.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        lastNameTextField.setSelectionColor(new java.awt.Color(153, 153, 255));
        lastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextFieldActionPerformed(evt);
            }
        });

        photoSubmitted.setFont(new java.awt.Font("sansserif", 0, 3)); // NOI18N
        photoSubmitted.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        photoSubmitted.setAlignmentX(0.5F);
        photoSubmitted.setIconTextGap(0);
        photoSubmitted.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                photoSubmittedComponentRemoved(evt);
            }
        });

        genderLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        genderLabel.setForeground(new java.awt.Color(255, 255, 255));
        genderLabel.setText("Gender:");
        genderLabel.setToolTipText("Please select your gender");

        hobbiesLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        hobbiesLabel.setForeground(new java.awt.Color(255, 255, 255));
        hobbiesLabel.setText("Hobbies:");
        hobbiesLabel.setToolTipText("Please enter your email in the space provided");

        ageLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        ageLabel.setForeground(new java.awt.Color(255, 255, 255));
        ageLabel.setText("Age:");
        ageLabel.setToolTipText("Please enter your age in the space provided");

        hobbyTextArea.setEditable(false);
        hobbyTextArea.setBackground(new java.awt.Color(63, 58, 118));
        hobbyTextArea.setColumns(20);
        hobbyTextArea.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        hobbyTextArea.setForeground(new java.awt.Color(255, 255, 255));
        hobbyTextArea.setLineWrap(true);
        hobbyTextArea.setRows(5);
        hobbyTextArea.setToolTipText("Please enter your hobbies");
        hobbyTextArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 58, 118), 5));
        hobbyTextArea.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(hobbyTextArea);

        ageSpinner.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        ageSpinner.setModel(new javax.swing.SpinnerNumberModel(Short.valueOf((short)0), Short.valueOf((short)0), Short.valueOf((short)200), Short.valueOf((short)1)));
        ageSpinner.setToolTipText("Please enter your age");
        ageSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ageSpinner.setEnabled(false);

        phoneFormattedText.setEditable(false);
        phoneFormattedText.setBackground(new java.awt.Color(63, 58, 118));
        phoneFormattedText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 58, 118), 5));
        phoneFormattedText.setForeground(new java.awt.Color(255, 255, 255));
        try {
            phoneFormattedText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(# # #) - # # # - # # # #")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        phoneFormattedText.setToolTipText("Please enter your phone number beginning with the area code");
        phoneFormattedText.setActionCommand("phone");
        phoneFormattedText.setCaretColor(new java.awt.Color(255, 255, 255));
        phoneFormattedText.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        phoneFormattedText.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        phoneFormattedText.setSelectionColor(new java.awt.Color(153, 153, 255));
        phoneFormattedText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneFormattedTextActionPerformed(evt);
            }
        });

        genderComboBox.setBackground(new java.awt.Color(63, 58, 118));
        genderComboBox.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        genderComboBox.setForeground(new java.awt.Color(255, 255, 255));
        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        genderComboBox.setSelectedIndex(-1);
        genderComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 58, 118), 5));
        genderComboBox.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        genderComboBox.setEnabled(false);

        phoneLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        phoneLabel.setForeground(new java.awt.Color(255, 255, 255));
        phoneLabel.setText("Phone:");
        phoneLabel.setToolTipText("Please enter your phone number in the space provided");

        DateOfBirthLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        DateOfBirthLabel.setForeground(new java.awt.Color(255, 255, 255));
        DateOfBirthLabel.setText("Date of Birth:");
        DateOfBirthLabel.setToolTipText("Please select a photo for your profile using the button provided");

        dateOfBirthTextField.setEditable(false);
        dateOfBirthTextField.setBackground(new java.awt.Color(63, 58, 118));
        dateOfBirthTextField.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        dateOfBirthTextField.setForeground(new java.awt.Color(255, 255, 255));
        dateOfBirthTextField.setToolTipText("Please enter your email");
        dateOfBirthTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 58, 118), 5));
        dateOfBirthTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        dateOfBirthTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        dateOfBirthTextField.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        dateOfBirthTextField.setSelectionColor(new java.awt.Color(63, 58, 118));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(emailLabel)
                                .addComponent(ageLabel)
                                .addComponent(phoneLabel)
                                .addComponent(hobbiesLabel))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ageSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1)
                                .addComponent(phoneFormattedText)
                                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(profilePhotoLabel)
                                .addComponent(DateOfBirthLabel))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dateOfBirthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(photoSubmitted, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(userRegistrationFormTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(genderLabel)
                            .addComponent(lastNameLabel)
                            .addComponent(firstNameLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(firstNameTextField)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                            .addComponent(genderComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(380, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(userRegistrationFormTitle)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phoneFormattedText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hobbiesLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateOfBirthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateOfBirthLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profilePhotoLabel)
                    .addComponent(photoSubmitted, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextFieldActionPerformed

    private void photoSubmittedComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_photoSubmittedComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_photoSubmittedComponentRemoved

    private void phoneFormattedTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneFormattedTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneFormattedTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DateOfBirthLabel;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JSpinner ageSpinner;
    private javax.swing.JTextField dateOfBirthTextField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel hobbiesLabel;
    private javax.swing.JTextArea hobbyTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JFormattedTextField phoneFormattedText;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JLabel photoSubmitted;
    private javax.swing.JLabel profilePhotoLabel;
    private javax.swing.JLabel userRegistrationFormTitle;
    // End of variables declaration//GEN-END:variables
}
