/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app_ui;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Darhlilove Botchway
 */
public class Lab2MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public Lab2MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        photoFileChooser = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        userRegistrationFormTitle = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        genderLabel = new javax.swing.JLabel();
        maleRadioButton = new javax.swing.JRadioButton();
        femaleRadioButton = new javax.swing.JRadioButton();
        otherGenderRadioButton = new javax.swing.JRadioButton();
        ageLabel = new javax.swing.JLabel();
        ageSpinner = new javax.swing.JSpinner();
        phoneFormattedText = new javax.swing.JFormattedTextField();
        phoneLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        profilePhotoLabel = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        photoChooserButton = new javax.swing.JButton();
        submittedPhoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(17, 7, 85));

        userRegistrationFormTitle.setFont(new java.awt.Font("Cantarell", 1, 30)); // NOI18N
        userRegistrationFormTitle.setForeground(new java.awt.Color(255, 255, 255));
        userRegistrationFormTitle.setText("User Registration Form");

        firstNameLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        firstNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        firstNameLabel.setText("First Name:");
        firstNameLabel.setToolTipText("Please enter your first name in the space provided");

        firstNameTextField.setBackground(new java.awt.Color(63, 58, 118));
        firstNameTextField.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        firstNameTextField.setForeground(new java.awt.Color(255, 255, 255));
        firstNameTextField.setToolTipText("Please enter your first name");
        firstNameTextField.setActionCommand("firstName");
        firstNameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 58, 118), 5));
        firstNameTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        firstNameTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        firstNameTextField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        firstNameTextField.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        firstNameTextField.setSelectionColor(new java.awt.Color(153, 153, 255));

        lastNameLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        lastNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        lastNameLabel.setText("Last Name:");
        lastNameLabel.setToolTipText("Please enter your last name in the space provided");

        lastNameTextField.setBackground(new java.awt.Color(63, 58, 118));
        lastNameTextField.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lastNameTextField.setForeground(new java.awt.Color(255, 255, 255));
        lastNameTextField.setToolTipText("Please enter your last name");
        lastNameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 58, 118), 5));
        lastNameTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        lastNameTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        lastNameTextField.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        lastNameTextField.setSelectionColor(new java.awt.Color(153, 153, 255));
        lastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextFieldActionPerformed(evt);
            }
        });

        genderLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        genderLabel.setForeground(new java.awt.Color(255, 255, 255));
        genderLabel.setText("Gender:");
        genderLabel.setToolTipText("Please select your gender");

        genderButtonGroup.add(maleRadioButton);
        maleRadioButton.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        maleRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        maleRadioButton.setText("Male");
        maleRadioButton.setActionCommand("gMale");
        maleRadioButton.setContentAreaFilled(false);
        maleRadioButton.setIconTextGap(10);
        maleRadioButton.setMultiClickThreshhold(1L);
        maleRadioButton.setName(""); // NOI18N
        maleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRadioButtonActionPerformed(evt);
            }
        });

        genderButtonGroup.add(femaleRadioButton);
        femaleRadioButton.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        femaleRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        femaleRadioButton.setText("Female");
        femaleRadioButton.setActionCommand("gFemale");
        femaleRadioButton.setIconTextGap(10);
        femaleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleRadioButtonActionPerformed(evt);
            }
        });

        genderButtonGroup.add(otherGenderRadioButton);
        otherGenderRadioButton.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        otherGenderRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        otherGenderRadioButton.setText("Other");
        otherGenderRadioButton.setActionCommand("gOther");
        otherGenderRadioButton.setIconTextGap(10);
        otherGenderRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherGenderRadioButtonActionPerformed(evt);
            }
        });

        ageLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        ageLabel.setForeground(new java.awt.Color(255, 255, 255));
        ageLabel.setText("Age:");
        ageLabel.setToolTipText("Please enter your age in the space provided");

        ageSpinner.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        ageSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 200, 1));
        ageSpinner.setToolTipText("Please enter your age");
        ageSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        phoneFormattedText.setBackground(new java.awt.Color(63, 58, 118));
        phoneFormattedText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 58, 118), 5));
        phoneFormattedText.setForeground(new java.awt.Color(255, 255, 255));
        try {
            phoneFormattedText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(# # #) - # # # - # # # #")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        phoneFormattedText.setToolTipText("Please enter your phone number beginning with the area code");
        phoneFormattedText.setActionCommand("phone");
        phoneFormattedText.setCaretColor(new java.awt.Color(255, 255, 255));
        phoneFormattedText.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        phoneFormattedText.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        phoneFormattedText.setSelectionColor(new java.awt.Color(153, 153, 255));
        phoneFormattedText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneFormattedTextActionPerformed(evt);
            }
        });

        phoneLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        phoneLabel.setForeground(new java.awt.Color(255, 255, 255));
        phoneLabel.setText("Phone:");
        phoneLabel.setToolTipText("Please enter your phone number in the space provided");

        emailLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel.setText("Email:");
        emailLabel.setToolTipText("Please enter your email in the space provided");

        emailTextField.setBackground(new java.awt.Color(63, 58, 118));
        emailTextField.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        emailTextField.setForeground(new java.awt.Color(255, 255, 255));
        emailTextField.setToolTipText("Please enter your email");
        emailTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 58, 118), 5));
        emailTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        emailTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        emailTextField.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        emailTextField.setSelectionColor(new java.awt.Color(153, 153, 255));

        profilePhotoLabel.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        profilePhotoLabel.setForeground(new java.awt.Color(255, 255, 255));
        profilePhotoLabel.setText("Profile Photo:");
        profilePhotoLabel.setToolTipText("Please select a photo for your profile using the button provided");

        submitButton.setBackground(new java.awt.Color(140, 130, 250));
        submitButton.setFont(new java.awt.Font("FreeSans", 1, 16)); // NOI18N
        submitButton.setText("Submit");
        submitButton.setToolTipText("Please click this button to submit your registration details");
        submitButton.setAlignmentX(0.5F);
        submitButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(140, 130, 250), 5, true));
        submitButton.setBorderPainted(false);
        submitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitButton.setMultiClickThreshhold(1L);
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        photoChooserButton.setBackground(new java.awt.Color(63, 58, 118));
        photoChooserButton.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        photoChooserButton.setForeground(new java.awt.Color(255, 255, 255));
        photoChooserButton.setText("Choose File");
        photoChooserButton.setAlignmentX(0.5F);
        photoChooserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photoChooserButtonActionPerformed(evt);
            }
        });

        submittedPhoto.setFont(new java.awt.Font("sansserif", 0, 3)); // NOI18N
        submittedPhoto.setAlignmentX(0.5F);
        submittedPhoto.setIconTextGap(0);
        submittedPhoto.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                submittedPhotoComponentRemoved(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(genderLabel)
                            .addComponent(lastNameLabel)
                            .addComponent(firstNameLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(maleRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(femaleRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(otherGenderRadioButton))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ageLabel)
                            .addComponent(phoneLabel)
                            .addComponent(emailLabel)
                            .addComponent(profilePhotoLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailTextField)
                            .addComponent(phoneFormattedText, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(ageSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(submittedPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(photoChooserButton))))
                .addGap(62, 211, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userRegistrationFormTitle)
                .addGap(257, 257, 257))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(userRegistrationFormTitle)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderLabel)
                    .addComponent(maleRadioButton)
                    .addComponent(femaleRadioButton)
                    .addComponent(otherGenderRadioButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneFormattedText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profilePhotoLabel)
                    .addComponent(photoChooserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submittedPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(submitButton)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        ageSpinner.getAccessibleContext().setAccessibleName("Age");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextFieldActionPerformed

    private void maleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleRadioButtonActionPerformed

    private void femaleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleRadioButtonActionPerformed

    private void otherGenderRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherGenderRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otherGenderRadioButtonActionPerformed

    private void phoneFormattedTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneFormattedTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneFormattedTextActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        try {
            // Declaring variables
            String firstName;
            String firstNameProperCase;
            String lastName;
            String lastNameProperCase;
            String gender;
            String email;
            String phone_unformatted;
            String phone_formatted;
            String confirmationMessage;
            int age;
            
            
            // Initialising variables
            firstName = this.firstNameTextField.getText().trim().toLowerCase();
            lastName = this.lastNameTextField.getText().trim().toLowerCase();
            gender = this.genderButtonGroup.getSelection().getActionCommand();
            email = this.emailTextField.getText().trim();
            phone_unformatted = this.phoneFormattedText.getText().trim().replaceAll("[^0-9]", "");
            phone_formatted = this.phoneFormattedText.getText().replaceAll(" ", "");
            age = Integer.parseInt(this.ageSpinner.getModel().getValue().toString());
            
            // Check if first name is not blank or contains no text or just whitespaces OR contains other characters aside letters and "-. "
            if (firstName.isBlank() || firstName.replaceAll("[a-z\\-. ]", "").length() != 0) {
                JOptionPane.showMessageDialog(rootPane, "Please enter a valid first name.", "Input Error!", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Check if last name is not blank or contains no text or just whitespaces OR contains other characters aside letters and "-. "
            if (lastName.isBlank() || lastName.replaceAll("[a-z\\-. ]", "").length() != 0) {
                JOptionPane.showMessageDialog(rootPane, "Please enter a valid last name.", "Input Error!", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Check if age is greater than 0
            if (age <= 0) {
                JOptionPane.showMessageDialog(rootPane, "Please enter a valid age.", "Input Error!", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Check if phone is less than 10 digits long OR phone begins with 0
            if (phone_unformatted.length() < 10 || phone_unformatted.indexOf("0") == 0) {
                JOptionPane.showMessageDialog(rootPane, "Please enter a valid phone number.", "Input Error!", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Check if email is blank or contains no text or just whitespaces 
            // OR email does not contain "@" or contains more than one "@" or beigns with "@"
            // OR the text after "@" does not contain "."
            // OR there is no text before "@"
            // OR there is no text between "@" and "." 
            // OR there is no text after "."
            // OR the length of email is less than 6 characters
            if (
                email.isBlank() ||                        // Email cannot be blank
                !email.contains("@") ||                   // Must contain an '@'
                email.indexOf("@") == 0 ||                // '@' cannot be the first character
                email.lastIndexOf("@") != email.indexOf("@") ||  // Multiple '@' are not allowed
                email.indexOf("@") == email.length() - 1 ||  // '@' cannot be the last character
                email.indexOf(".", email.indexOf("@")) == -1 ||  // '.' must exist after '@'
                email.indexOf(".", email.indexOf("@")) == email.indexOf("@") + 1 ||  // '.' cannot immediately follow '@'
                email.substring(email.lastIndexOf(".") + 1).trim().length() < 2 ||  // Text after '.' must be at least 2 characters
                email.length() < 6                        // Minimum length check
            ) {
                JOptionPane.showMessageDialog(rootPane, "Please enter a valid email.", "Input Error!", JOptionPane.ERROR_MESSAGE);
                return;
            } 
            
            // Check if photo is uploaded
            if (this.submittedPhoto.getIcon() == null){
                JOptionPane.showMessageDialog(rootPane, "Please upload an image.", "Error - No image", JOptionPane.ERROR_MESSAGE);
                    return;
            }
            
            firstNameProperCase = firstName.substring(0,1).toUpperCase() + firstName.substring(1);
            lastNameProperCase = lastName.substring(0,1).toUpperCase() + lastName.substring(1);

            confirmationMessage = "User Profile Information"
                    + "\n"
                    + "\n First name: " + firstNameProperCase
                    + "\n Last name: " + lastNameProperCase
                    + "\n Gender: " + gender.substring(1)
                    + "\n Age: " + age
                    + "\n Phone: " + phone_formatted
                    + "\n Email: " + email;

            JOptionPane.showMessageDialog(rootPane, confirmationMessage, "Account created!", HEIGHT, this.submittedPhoto.getIcon());            
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(rootPane, "Please select your gender", "Selection Error!", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Something went wrong!", "Ooops!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void photoChooserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photoChooserButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        
        FileNameExtensionFilter imageFilter = new FileNameExtensionFilter("Image Files (JPG, JPEG, PNG, GIF)", "jpg", "jpeg", "png", "gif");
        file.setFileFilter(imageFilter);
        
        if (file.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
            try {
                BufferedImage img = ImageIO.read(file.getSelectedFile());
                Image edited_image;
                edited_image = img.getScaledInstance(120, 120, Image.SCALE_SMOOTH);
                if (edited_image != null) {
                    this.submittedPhoto.setIcon(new ImageIcon(edited_image));
                }
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Please upload image correctly.", "Error - Incorrect image", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_photoChooserButtonActionPerformed

    private void submittedPhotoComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_submittedPhotoComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_submittedPhotoComponentRemoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab2MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab2MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab2MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab2MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab2MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageLabel;
    private javax.swing.JSpinner ageSpinner;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JRadioButton maleRadioButton;
    private javax.swing.JRadioButton otherGenderRadioButton;
    private javax.swing.JFormattedTextField phoneFormattedText;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JButton photoChooserButton;
    private javax.swing.JFileChooser photoFileChooser;
    private javax.swing.JLabel profilePhotoLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel submittedPhoto;
    private javax.swing.JLabel userRegistrationFormTitle;
    // End of variables declaration//GEN-END:variables
}
